/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.ElaborarPlanDeCurso.criteriosDeEvaluacion;
import clases.CriterioDeEvaluacion;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Juuan
 */
public class AgregarCriterioDeEvaluacion extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCriterioDeEvaluacion
     */
    public AgregarCriterioDeEvaluacion() {
        initComponents();
    }
    public boolean validarCampos(){
        if(unidadEvaluadaIn.getText() == "" || fechaIn.getText() == "" || criterioDeEvaluacionIn.getText() == "" || instrumentosIn.getText() == "" || porcentajeIn.getText() == ""){
            return false;
        }
        return true;
    }
    
    public boolean validarFecha(String fecha){
        SimpleDateFormat estructura = new SimpleDateFormat("yyyy-mm-dd");
        estructura.setLenient(false);
        try{
            estructura.parse(fecha);
        }catch(ParseException excepcion){
            
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        criterioDeEvaluacionText = new javax.swing.JLabel();
        unidadEvaluadaText = new javax.swing.JLabel();
        fechasText = new javax.swing.JLabel();
        criterioDeEvaluacionEntradaText = new javax.swing.JLabel();
        instrumentosText = new javax.swing.JLabel();
        porcentajeText = new javax.swing.JLabel();
        unidadEvaluadaIn = new javax.swing.JTextField();
        fechaIn = new javax.swing.JTextField();
        criterioDeEvaluacionIn = new javax.swing.JTextField();
        instrumentosIn = new javax.swing.JTextField();
        porcentajeIn = new javax.swing.JTextField();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        criterioDeEvaluacionText.setText("Criterio de Evaluación; ");

        unidadEvaluadaText.setText("Unidad(es) Evaluadad(as): ");

        fechasText.setText("Fecha limite (aaaa-mm-dd): ");

        criterioDeEvaluacionEntradaText.setText("Criterio de evaluacion: ");

        instrumentosText.setText("Instrumentos: ");

        porcentajeText.setText("Porcentaje: ");

        unidadEvaluadaIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unidadEvaluadaInKeyTyped(evt);
            }
        });

        fechaIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechaInKeyTyped(evt);
            }
        });

        criterioDeEvaluacionIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                criterioDeEvaluacionInKeyTyped(evt);
            }
        });

        instrumentosIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                instrumentosInKeyTyped(evt);
            }
        });

        porcentajeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeInActionPerformed(evt);
            }
        });
        porcentajeIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                porcentajeInKeyTyped(evt);
            }
        });

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("(ejemplo: 1-4)");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(criterioDeEvaluacionEntradaText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(criterioDeEvaluacionIn))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(instrumentosText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(instrumentosIn))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(porcentajeText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(cancelarButton)
                                        .addGap(0, 96, Short.MAX_VALUE))
                                    .addComponent(porcentajeIn)))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(criterioDeEvaluacionText))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechasText)
                            .addComponent(unidadEvaluadaText))
                        .addGap(2, 2, 2)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaIn)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(unidadEvaluadaIn))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criterioDeEvaluacionText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadEvaluadaText)
                    .addComponent(unidadEvaluadaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechasText)
                    .addComponent(fechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterioDeEvaluacionEntradaText)
                    .addComponent(criterioDeEvaluacionIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrumentosText)
                    .addComponent(instrumentosIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcentajeText)
                    .addComponent(porcentajeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton)
                    .addComponent(cancelarButton))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void porcentajeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentajeInActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        if (!validarCampos() || !validarFecha(fechaIn.getText())){
            JOptionPane.showMessageDialog(this, "Se deben llenar todos los campos o la fecha esta ingresada incorrectamente");
        }else{
            CriterioDeEvaluacion criterioDeEvaluacion = new CriterioDeEvaluacion();
            criterioDeEvaluacion.setUnidadesEvaluadas(unidadEvaluadaIn.getText());
            criterioDeEvaluacion.setFecha(Date.valueOf(fechaIn.getText()));
            criterioDeEvaluacion.setCriterioEvaluacion(criterioDeEvaluacionIn.getText());
            criterioDeEvaluacion.setInstrumento(instrumentosIn.getText());
            criterioDeEvaluacion.setPorcentaje(porcentajeIn.getText());
            ElaborarPlanDeCurso.criteriosDeEvaluacion.add(criterioDeEvaluacion);
            dispose();
       }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void unidadEvaluadaInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadEvaluadaInKeyTyped
        char caracteres= evt.getKeyChar();
        if ((caracteres<'0'||caracteres>'9') && caracteres != '-') evt.consume();
        if(unidadEvaluadaIn.getText().length() >= 5){
            evt.consume();
        }
    }//GEN-LAST:event_unidadEvaluadaInKeyTyped

    private void fechaInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaInKeyTyped
        char caracteres= evt.getKeyChar();
        if ((caracteres<'0'||caracteres>'9') && caracteres != '-') evt.consume();
        if(fechaIn.getText().length() >= 10){
            evt.consume();
        }
    }//GEN-LAST:event_fechaInKeyTyped

    private void criterioDeEvaluacionInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_criterioDeEvaluacionInKeyTyped
        if(criterioDeEvaluacionIn.getText().length() >= 1000){
            evt.consume();
        }
    }//GEN-LAST:event_criterioDeEvaluacionInKeyTyped

    private void instrumentosInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_instrumentosInKeyTyped
        if(instrumentosIn.getText().length() >= 500){
            evt.consume();
        }
    }//GEN-LAST:event_instrumentosInKeyTyped

    private void porcentajeInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_porcentajeInKeyTyped
        if(porcentajeIn.getText().length() >= 50){
            evt.consume();
        }
    }//GEN-LAST:event_porcentajeInKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCriterioDeEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCriterioDeEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCriterioDeEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCriterioDeEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCriterioDeEvaluacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel criterioDeEvaluacionEntradaText;
    private javax.swing.JTextField criterioDeEvaluacionIn;
    private javax.swing.JLabel criterioDeEvaluacionText;
    private javax.swing.JTextField fechaIn;
    private javax.swing.JLabel fechasText;
    private javax.swing.JTextField instrumentosIn;
    private javax.swing.JLabel instrumentosText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField porcentajeIn;
    private javax.swing.JLabel porcentajeText;
    private javax.swing.JTextField unidadEvaluadaIn;
    private javax.swing.JLabel unidadEvaluadaText;
    // End of variables declaration//GEN-END:variables
}
