/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import basedatos.DataBase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Juuan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    public boolean buscarUsuario(String numeroDePersonal, String contrasenia){
        boolean encontrado = false;
        String BUSCAR_USUARIO = "SELECT* FROM usuario_contrasena WHERE numeroPersonal = '"+numeroDePersonal+"' AND contraseña = '"+contrasenia+"';";
        String numeroDePersonalObtenido= "";
        String contraseniaObtenida = "";
        Connection conexion = DataBase.getDataBaseConnection();
        try{
            PreparedStatement statement = conexion.prepareStatement(BUSCAR_USUARIO);
            ResultSet resultado = statement.executeQuery();
            while(resultado.next()){
                numeroDePersonalObtenido = resultado.getString("numeroPersonal");
                contraseniaObtenida = resultado.getString("Contraseña");
                if(numeroDePersonal.equals(numeroDePersonalObtenido) && contrasenia.equals(contraseniaObtenida)){
                    encontrado = true;
                }
            }
            return encontrado;
        }catch(SQLException excepcion){
            
        }
        return encontrado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        numeroDePersonalIn = new javax.swing.JTextField();
        numeroDePersonalText = new javax.swing.JLabel();
        contraseniaText = new javax.swing.JLabel();
        aceptarButton = new javax.swing.JButton();
        contraseniaIn = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numeroDePersonalIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDePersonalInActionPerformed(evt);
            }
        });
        numeroDePersonalIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroDePersonalInKeyTyped(evt);
            }
        });

        numeroDePersonalText.setText("Número de personal: ");

        contraseniaText.setText("Contraseña: ");

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        contraseniaIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseniaInKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numeroDePersonalText)
                    .addComponent(contraseniaText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeroDePersonalIn)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(aceptarButton))
                    .addComponent(contraseniaIn, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroDePersonalIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroDePersonalText))
                .addGap(26, 26, 26)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseniaText)
                    .addComponent(contraseniaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(aceptarButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroDePersonalInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDePersonalInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDePersonalInActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        if(numeroDePersonalIn.getText().length() == 0 || contraseniaIn.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Debes llena los campos");
        }else{
            if(!buscarUsuario(numeroDePersonalIn.getText(), contraseniaIn.getText())){
                JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            }else{
                SeleccionarAcademia.setNumeroDePersonal(numeroDePersonalIn.getText());
                SeleccionarAcademia seleccionar = new SeleccionarAcademia();
                seleccionar.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void contraseniaInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseniaInKeyTyped
        if(contraseniaIn.getText().length() >= 45){
            JOptionPane.showMessageDialog(this, "Solo se aceptan un maximo de 45 caracteres");
        }
    }//GEN-LAST:event_contraseniaInKeyTyped

    private void numeroDePersonalInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroDePersonalInKeyTyped
        if (numeroDePersonalIn.getText().length() >= 100){
            JOptionPane.showMessageDialog(this, "Solo se aceptan un maximo de 100 caracteres");
        }
    }//GEN-LAST:event_numeroDePersonalInKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JPasswordField contraseniaIn;
    private javax.swing.JLabel contraseniaText;
    private javax.swing.JTextField numeroDePersonalIn;
    private javax.swing.JLabel numeroDePersonalText;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
