/*

 *  Derechos de autor: UV-software(c)
 *  @auto: Juan Carlos Domínguez Dominguez
 *  @nombre: Control de academias
 *  @versión 0.3.2
 *  Este producto no puede ser intercambiado bajo ninguna circunstancia
	
 */

package GUI;

import DAO.PlanDeCursoDAO;
import clases.Curso;
import clases.ExperienciaEducativa;
import clases.PlanDeCurso;
import clases.Profesor;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author Juuan
 */
public class PantallaCoordinador extends javax.swing.JFrame {
    public static Profesor coordinador;
    private static int posicionCursoOAcademia;
    private static int posicionExperiencia;
    private Curso curso = new Curso();
    private PlanDeCursoDAO planDeCursoDAO = new PlanDeCursoDAO();
    private PlanDeCurso planDeCurso = new PlanDeCurso();

    public static int getPosicionCursoOAcademia() {
        return posicionCursoOAcademia;
    }

    public static void setPosicionCursoOAcademia(int posicionCursoOAcademia) {
        PantallaCoordinador.posicionCursoOAcademia = posicionCursoOAcademia;
    }

    public static int getPosicionExperiencia() {
        return posicionExperiencia;
    }

    public static void setPosicionExperiencia(int posicionExperiencia) {
        PantallaCoordinador.posicionExperiencia = posicionExperiencia;
    }

    public static Profesor getCoordinador() {
        return coordinador;
    }

    public static void setCoordinador(Profesor coordinador) {
        PantallaCoordinador.coordinador = coordinador;
    }

    /**
     * Creates new form PantallaCoordinador
     */
    public PantallaCoordinador() {
        initComponents();
        habilitarBotones();
    }
    
    public void habilitarBotones(){
        consultarJAButton.setEnabled(false);
        visualizarAPButton.setEnabled(false);
        visualizarMJAButton.setEnabled(false);
        visualizarPCButton.setEnabled(true);
        visualizarPTButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        imagenUsuario = new javax.swing.JLabel();
        consultarJAButton = new javax.swing.JButton();
        visualizarMJAButton = new javax.swing.JButton();
        visualizarAPButton = new javax.swing.JButton();
        visualizarPCButton = new javax.swing.JButton();
        visualizarPTButton = new javax.swing.JButton();
        seleccionarExperienciaButton = new javax.swing.JButton();
        cerrarSesionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagenUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultarJAButton.setText("Consultar juntas de academia");

        visualizarMJAButton.setText("Visualizar minuta de junta de academia");

        visualizarAPButton.setText("Visualizar avance programatico");

        visualizarPCButton.setText("Visualizar plan de curso");
        visualizarPCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarPCButtonActionPerformed(evt);
            }
        });

        visualizarPTButton.setText("Visualizar plan de trabajo");
        visualizarPTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarPTButtonActionPerformed(evt);
            }
        });

        seleccionarExperienciaButton.setText("Seleccionar otra experiencia educativa");
        seleccionarExperienciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarExperienciaButtonActionPerformed(evt);
            }
        });

        cerrarSesionButton.setText("Cerrar sesión");
        cerrarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagenUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(visualizarMJAButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultarJAButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(visualizarAPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(visualizarPCButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(visualizarPTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(seleccionarExperienciaButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(cerrarSesionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(consultarJAButton)
                        .addGap(18, 18, 18)
                        .addComponent(visualizarMJAButton)
                        .addGap(18, 18, 18)
                        .addComponent(visualizarAPButton)
                        .addGap(18, 18, 18)
                        .addComponent(visualizarPCButton)
                        .addGap(18, 18, 18)
                        .addComponent(visualizarPTButton))
                    .addComponent(imagenUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(seleccionarExperienciaButton)
                .addGap(18, 18, 18)
                .addComponent(cerrarSesionButton)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizarPTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarPTButtonActionPerformed
        
    }//GEN-LAST:event_visualizarPTButtonActionPerformed

    private void visualizarPCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarPCButtonActionPerformed
        curso = coordinador.getAcademias().get(posicionCursoOAcademia).getExperienciasEducativas().get(posicionExperiencia).getCurso();
        if (curso == null) {
            JOptionPane.showMessageDialog(this, "La experiencia educativa no tiene un curso asignado.");
        } else {
            try {
                planDeCurso = planDeCursoDAO.obtenerPlanDeCursoPorCurso(curso);
                if (planDeCurso.getEstado().equals("Incompleto")) {
                    JOptionPane.showMessageDialog(this, "No hay un plan de curso que mostrar.");
                } else {
                    VisualizarPlanDeCurso.setProfesor(coordinador);
                    VisualizarPlanDeCurso.setPosicionCurso(posicionCursoOAcademia);
                    VisualizarPlanDeCurso visualizarPlanDeCurso = new VisualizarPlanDeCurso();
                    visualizarPlanDeCurso.setVisible(true);
                }
            } catch (NullPointerException excepcion) {
                java.util.logging.Logger.getLogger(PantallaCoordinador.class.getName()).log(Level.SEVERE, null, excepcion);
                JOptionPane.showMessageDialog(this, "No hay un plan de curso que mostrar");
            }
        }
    }//GEN-LAST:event_visualizarPCButtonActionPerformed

    private void seleccionarExperienciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarExperienciaButtonActionPerformed
        SeleccionarExperienciaEducativa seleccionar = new SeleccionarExperienciaEducativa();
        seleccionar.setVisible(true);
        dispose();
    }//GEN-LAST:event_seleccionarExperienciaButtonActionPerformed

    private void cerrarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cerrarSesionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCoordinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesionButton;
    private javax.swing.JButton consultarJAButton;
    private javax.swing.JLabel imagenUsuario;
    private javax.swing.JPanel panel;
    private javax.swing.JButton seleccionarExperienciaButton;
    private javax.swing.JButton visualizarAPButton;
    private javax.swing.JButton visualizarMJAButton;
    private javax.swing.JButton visualizarPCButton;
    private javax.swing.JButton visualizarPTButton;
    // End of variables declaration//GEN-END:variables
}
