/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Profesor;

/**
 *
 * @author Juuan
 */
public class VisualizarPlanDeCurso extends javax.swing.JFrame {
    private static Profesor profesor;
    private static int posicionCurso;

    public static int getPosicionCurso() {
        return posicionCurso;
    }

    public static void setPosicionCurso(int posicionCurso) {
        VisualizarPlanDeCurso.posicionCurso = posicionCurso;
    }

    public static Profesor getProfesor() {
        return profesor;
    }

    public static void setProfesor(Profesor profesor) {
        VisualizarPlanDeCurso.profesor = profesor;
    }
    /**
     * Creates new form VisualizarPlanDeCurso
     */
    public VisualizarPlanDeCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        claveNrcText = new javax.swing.JLabel();
        academicoText = new javax.swing.JLabel();
        experienciaEducativaText = new javax.swing.JLabel();
        programaEducativoText = new javax.swing.JLabel();
        bloqueText = new javax.swing.JLabel();
        seccionText = new javax.swing.JLabel();
        periodoText = new javax.swing.JLabel();
        objetivoGeneralText = new javax.swing.JLabel();
        objetivoGeneralIn = new javax.swing.JTextField();
        planeacionText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        planeacionTable = new javax.swing.JTable();
        bibliografiaText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bibliografiaTable = new javax.swing.JTable();
        calendarioEvaluacionText = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        calendarioEvaluacionTable = new javax.swing.JTable();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        claveNrcText.setText("CLAVE NRC: ");

        academicoText.setText("ACADÉMICO: ");

        experienciaEducativaText.setText("E.E: ");

        programaEducativoText.setText("P.E: ");

        bloqueText.setText("Bloque: ");

        seccionText.setText("Sección: ");

        periodoText.setText("PERIODO: ");

        objetivoGeneralText.setText("OBJETIVO GENERAL: ");

        planeacionText.setText("PLANEACIÓN: ");

        planeacionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Unidad", "Temas", "Fechas", "Tareas y prácticas", "Técnica didactica"
            }
        ));
        jScrollPane1.setViewportView(planeacionTable);

        bibliografiaText.setText("BIBLIOGRAFÍA: ");

        bibliografiaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Autor(es)", "Título de libro", "Editorial", "Año"
            }
        ));
        jScrollPane2.setViewportView(bibliografiaTable);

        calendarioEvaluacionText.setText("CALENDARIO DE EVALUACIÓN: ");

        calendarioEvaluacionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Unidad", "Fechas", "Criterio de evaluación: ", "Instrumento", "Porcentaje"
            }
        ));
        jScrollPane3.setViewportView(calendarioEvaluacionTable);

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(objetivoGeneralIn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calendarioEvaluacionText)
                            .addComponent(bibliografiaText)
                            .addComponent(planeacionText)
                            .addComponent(objetivoGeneralText)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(academicoText)
                                .addGap(279, 279, 279)
                                .addComponent(periodoText))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(claveNrcText)
                                .addGap(67, 67, 67)
                                .addComponent(experienciaEducativaText)
                                .addGap(153, 153, 153)
                                .addComponent(programaEducativoText)
                                .addGap(198, 198, 198)
                                .addComponent(bloqueText)
                                .addGap(83, 83, 83)
                                .addComponent(seccionText)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(90, 90, 90))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(salirButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claveNrcText)
                    .addComponent(experienciaEducativaText)
                    .addComponent(programaEducativoText)
                    .addComponent(bloqueText)
                    .addComponent(seccionText))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(academicoText)
                    .addComponent(periodoText))
                .addGap(27, 27, 27)
                .addComponent(objetivoGeneralText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(objetivoGeneralIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(planeacionText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bibliografiaText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calendarioEvaluacionText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salirButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarPlanDeCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarPlanDeCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarPlanDeCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarPlanDeCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarPlanDeCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academicoText;
    private javax.swing.JTable bibliografiaTable;
    private javax.swing.JLabel bibliografiaText;
    private javax.swing.JLabel bloqueText;
    private javax.swing.JTable calendarioEvaluacionTable;
    private javax.swing.JLabel calendarioEvaluacionText;
    private javax.swing.JLabel claveNrcText;
    private javax.swing.JLabel experienciaEducativaText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField objetivoGeneralIn;
    private javax.swing.JLabel objetivoGeneralText;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel periodoText;
    private javax.swing.JTable planeacionTable;
    private javax.swing.JLabel planeacionText;
    private javax.swing.JLabel programaEducativoText;
    private javax.swing.JButton salirButton;
    private javax.swing.JLabel seccionText;
    // End of variables declaration//GEN-END:variables
}
